<?php

/**
 * BasePlayers
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $id
 * @property int $match_id
 * @property int $map_id
 * @property varchar $player_key
 * @property enum $team
 * @property varchar $ip
 * @property varchar $steamid
 * @property enum $first_side
 * @property enum $current_side
 * @property varchar $pseudo
 * @property int $nb_kill
 * @property int $assist
 * @property int $death
 * @property int $point
 * @property int $hs
 * @property int $defuse
 * @property int $bombe
 * @property int $tk
 * @property int $nb1
 * @property int $nb2
 * @property int $nb3
 * @property int $nb4
 * @property int $nb5
 * @property int $nb1kill
 * @property int $nb2kill
 * @property int $nb3kill
 * @property int $nb4kill
 * @property int $nb5kill
 * @property int $pluskill
 * @property int $firstkill
 * @property Matchs $Match
 * @property Maps $Map
 * @property Doctrine_Collection $PlayersSnapshot
 * @property Doctrine_Collection $RoundSummary
 * @property Doctrine_Collection $PlayerKill
 * @property Doctrine_Collection $PlayersHeatmap
 *
 * @method int getId() Returns the current record's "id" value
 * @method int getMatchId() Returns the current record's "match_id" value
 * @method int getMapId() Returns the current record's "map_id" value
 * @method varchar getPlayerKey() Returns the current record's "player_key" value
 * @method enum getTeam() Returns the current record's "team" value
 * @method varchar getIp() Returns the current record's "ip" value
 * @method varchar getSteamid() Returns the current record's "steamid" value
 * @method enum getFirstSide() Returns the current record's "first_side" value
 * @method enum getCurrentSide() Returns the current record's "current_side" value
 * @method varchar getPseudo() Returns the current record's "pseudo" value
 * @method int getNbKill() Returns the current record's "nb_kill" value
 * @method int getAssist() Returns the current record's "assist" value
 * @method int getDeath() Returns the current record's "death" value
 * @method int getPoint() Returns the current record's "point" value
 * @method int getHs() Returns the current record's "hs" value
 * @method int getDefuse() Returns the current record's "defuse" value
 * @method int getBombe() Returns the current record's "bombe" value
 * @method int getTk() Returns the current record's "tk" value
 * @method int getNb1() Returns the current record's "nb1" value
 * @method int getNb2() Returns the current record's "nb2" value
 * @method int getNb3() Returns the current record's "nb3" value
 * @method int getNb4() Returns the current record's "nb4" value
 * @method int getNb5() Returns the current record's "nb5" value
 * @method int getNb1kill() Returns the current record's "nb1kill" value
 * @method int getNb2kill() Returns the current record's "nb2kill" value
 * @method int getNb3kill() Returns the current record's "nb3kill" value
 * @method int getNb4kill() Returns the current record's "nb4kill" value
 * @method int getNb5kill() Returns the current record's "nb5kill" value
 * @method int getPluskill() Returns the current record's "pluskill" value
 * @method int getFirstkill() Returns the current record's "firstkill" value
 * @method Matchs getMatch() Returns the current record's "Match" value
 * @method Maps getMap() Returns the current record's "Map" value
 * @method Doctrine_Collection getPlayersSnapshot() Returns the current record's "PlayersSnapshot" collection
 * @method Doctrine_Collection getRoundSummary() Returns the current record's "RoundSummary" collection
 * @method Doctrine_Collection getPlayerKill() Returns the current record's "PlayerKill" collection
 * @method Doctrine_Collection getPlayersHeatmap() Returns the current record's "PlayersHeatmap" collection
 * @method Players setId() Sets the current record's "id" value
 * @method Players setMatchId() Sets the current record's "match_id" value
 * @method Players setMapId() Sets the current record's "map_id" value
 * @method Players setPlayerKey() Sets the current record's "player_key" value
 * @method Players setTeam() Sets the current record's "team" value
 * @method Players setIp() Sets the current record's "ip" value
 * @method Players setSteamid() Sets the current record's "steamid" value
 * @method Players setFirstSide() Sets the current record's "first_side" value
 * @method Players setCurrentSide() Sets the current record's "current_side" value
 * @method Players setPseudo() Sets the current record's "pseudo" value
 * @method Players setNbKill() Sets the current record's "nb_kill" value
 * @method Players setAssist() Sets the current record's "assist" value
 * @method Players setDeath() Sets the current record's "death" value
 * @method Players setPoint() Sets the current record's "point" value
 * @method Players setHs() Sets the current record's "hs" value
 * @method Players setDefuse() Sets the current record's "defuse" value
 * @method Players setBombe() Sets the current record's "bombe" value
 * @method Players setTk() Sets the current record's "tk" value
 * @method Players setNb1() Sets the current record's "nb1" value
 * @method Players setNb2() Sets the current record's "nb2" value
 * @method Players setNb3() Sets the current record's "nb3" value
 * @method Players setNb4() Sets the current record's "nb4" value
 * @method Players setNb5() Sets the current record's "nb5" value
 * @method Players setNb1kill() Sets the current record's "nb1kill" value
 * @method Players setNb2kill() Sets the current record's "nb2kill" value
 * @method Players setNb3kill() Sets the current record's "nb3kill" value
 * @method Players setNb4kill() Sets the current record's "nb4kill" value
 * @method Players setNb5kill() Sets the current record's "nb5kill" value
 * @method Players setPluskill() Sets the current record's "pluskill" value
 * @method Players setFirstkill() Sets the current record's "firstkill" value
 * @method Players setMatch() Sets the current record's "Match" value
 * @method Players setMap() Sets the current record's "Map" value
 * @method Players setPlayersSnapshot() Sets the current record's "PlayersSnapshot" collection
 * @method Players setRoundSummary() Sets the current record's "RoundSummary" collection
 * @method Players setPlayerKill() Sets the current record's "PlayerKill" collection
 * @method Players setPlayersHeatmap() Sets the current record's "PlayersHeatmap" collection
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('players');
        $this->hasColumn('id', 'integer', 20, [
            'primary' => true,
            'type' => 'integer',
            'autoincrement' => true,
            'length' => 20,
        ]);
        $this->hasColumn('match_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('map_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('player_key', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('team', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'a',
                1 => 'b',
                2 => 'other',
            ],
            'default' => 'other',
        ]);
        $this->hasColumn('ip', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('steamid', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('first_side', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'ct',
                1 => 't',
                2 => 'other',
            ],
        ]);
        $this->hasColumn('current_side', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'ct',
                1 => 't',
                2 => 'other',
            ],
        ]);
        $this->hasColumn('pseudo', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('nb_kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('assist', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('death', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('point', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('hs', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('defuse', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('bombe', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('tk', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb1', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb2', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb3', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb4', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb5', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb1kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb2kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb3kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb4kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb5kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('pluskill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('firstkill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Matchs as Match', [
            'local' => 'match_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('Maps as Map', [
            'local' => 'map_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasMany('PlayersSnapshot', [
            'local' => 'id',
            'foreign' => 'player_id']);

        $this->hasMany('RoundSummary', [
            'local' => 'id',
            'foreign' => 'best_killer']);

        $this->hasMany('PlayerKill', [
            'local' => 'id',
            'foreign' => 'killer_id']);

        $this->hasMany('PlayersHeatmap', [
            'local' => 'id',
            'foreign' => 'player_id']);

        $timestampable0 = new Doctrine_Template_Timestampable;
        $this->actAs($timestampable0);
    }
}
