<?php

/**
 * BaseRound
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $id
 * @property int $match_id
 * @property int $map_id
 * @property varchar $event_name
 * @property text $event_text
 * @property int $event_time
 * @property int $kill_id
 * @property int $round_id
 * @property Matchs $Match
 * @property Maps $Map
 * @property PlayerKill $Kill
 *
 * @method int getId() Returns the current record's "id" value
 * @method int getMatchId() Returns the current record's "match_id" value
 * @method int getMapId() Returns the current record's "map_id" value
 * @method varchar getEventName() Returns the current record's "event_name" value
 * @method text getEventText() Returns the current record's "event_text" value
 * @method int getEventTime() Returns the current record's "event_time" value
 * @method int getKillId() Returns the current record's "kill_id" value
 * @method int getRoundId() Returns the current record's "round_id" value
 * @method Matchs getMatch() Returns the current record's "Match" value
 * @method Maps getMap() Returns the current record's "Map" value
 * @method PlayerKill getKill() Returns the current record's "Kill" value
 * @method Round setId() Sets the current record's "id" value
 * @method Round setMatchId() Sets the current record's "match_id" value
 * @method Round setMapId() Sets the current record's "map_id" value
 * @method Round setEventName() Sets the current record's "event_name" value
 * @method Round setEventText() Sets the current record's "event_text" value
 * @method Round setEventTime() Sets the current record's "event_time" value
 * @method Round setKillId() Sets the current record's "kill_id" value
 * @method Round setRoundId() Sets the current record's "round_id" value
 * @method Round setMatch() Sets the current record's "Match" value
 * @method Round setMap() Sets the current record's "Map" value
 * @method Round setKill() Sets the current record's "Kill" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRound extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('round');
        $this->hasColumn('id', 'integer', 20, [
            'primary' => true,
            'type' => 'integer',
            'autoincrement' => true,
            'length' => 20,
        ]);
        $this->hasColumn('match_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('map_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('event_name', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('event_text', 'text', null, [
            'type' => 'text',
        ]);
        $this->hasColumn('event_time', 'integer', 5, [
            'type' => 'integer',
            'length' => 5,
        ]);
        $this->hasColumn('kill_id', 'integer', 20, [
            'type' => 'integer',
            'length' => 20,
        ]);
        $this->hasColumn('round_id', 'integer', 20, [
            'type' => 'integer',
            'length' => 20,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Matchs as Match', [
            'local' => 'match_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('Maps as Map', [
            'local' => 'map_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('PlayerKill as Kill', [
            'local' => 'kill_id',
            'foreign' => 'id',
            'onDelete' => 'SET NULL']);

        $timestampable0 = new Doctrine_Template_Timestampable;
        $this->actAs($timestampable0);
    }
}
