<?php

/**
 * BaseRoundSummary
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $id
 * @property int $match_id
 * @property int $map_id
 * @property bool $bomb_planted
 * @property bool $bomb_defused
 * @property bool $bomb_exploded
 * @property enum $win_type
 * @property enum $team_win
 * @property bool $ct_win
 * @property bool $t_win
 * @property int $score_a
 * @property int $score_b
 * @property int $best_killer
 * @property int $best_killer_nb
 * @property bool $best_killer_fk
 * @property text $best_action_type
 * @property text $best_action_param
 * @property varchar $backup_file_name
 * @property int $round_id
 * @property Matchs $Match
 * @property Maps $Map
 * @property Players $BestKiller
 *
 * @method int getId() Returns the current record's "id" value
 * @method int getMatchId() Returns the current record's "match_id" value
 * @method int getMapId() Returns the current record's "map_id" value
 * @method bool getBombPlanted() Returns the current record's "bomb_planted" value
 * @method bool getBombDefused() Returns the current record's "bomb_defused" value
 * @method bool getBombExploded() Returns the current record's "bomb_exploded" value
 * @method enum getWinType() Returns the current record's "win_type" value
 * @method enum getTeamWin() Returns the current record's "team_win" value
 * @method bool getCtWin() Returns the current record's "ct_win" value
 * @method bool getTWin() Returns the current record's "t_win" value
 * @method int getScoreA() Returns the current record's "score_a" value
 * @method int getScoreB() Returns the current record's "score_b" value
 * @method int getBestKiller() Returns the current record's "best_killer" value
 * @method int getBestKillerNb() Returns the current record's "best_killer_nb" value
 * @method bool getBestKillerFk() Returns the current record's "best_killer_fk" value
 * @method text getBestActionType() Returns the current record's "best_action_type" value
 * @method text getBestActionParam() Returns the current record's "best_action_param" value
 * @method varchar getBackupFileName() Returns the current record's "backup_file_name" value
 * @method int getRoundId() Returns the current record's "round_id" value
 * @method Matchs getMatch() Returns the current record's "Match" value
 * @method Maps getMap() Returns the current record's "Map" value
 * @method Players getBestKiller() Returns the current record's "BestKiller" value
 * @method RoundSummary setId() Sets the current record's "id" value
 * @method RoundSummary setMatchId() Sets the current record's "match_id" value
 * @method RoundSummary setMapId() Sets the current record's "map_id" value
 * @method RoundSummary setBombPlanted() Sets the current record's "bomb_planted" value
 * @method RoundSummary setBombDefused() Sets the current record's "bomb_defused" value
 * @method RoundSummary setBombExploded() Sets the current record's "bomb_exploded" value
 * @method RoundSummary setWinType() Sets the current record's "win_type" value
 * @method RoundSummary setTeamWin() Sets the current record's "team_win" value
 * @method RoundSummary setCtWin() Sets the current record's "ct_win" value
 * @method RoundSummary setTWin() Sets the current record's "t_win" value
 * @method RoundSummary setScoreA() Sets the current record's "score_a" value
 * @method RoundSummary setScoreB() Sets the current record's "score_b" value
 * @method RoundSummary setBestKiller() Sets the current record's "best_killer" value
 * @method RoundSummary setBestKillerNb() Sets the current record's "best_killer_nb" value
 * @method RoundSummary setBestKillerFk() Sets the current record's "best_killer_fk" value
 * @method RoundSummary setBestActionType() Sets the current record's "best_action_type" value
 * @method RoundSummary setBestActionParam() Sets the current record's "best_action_param" value
 * @method RoundSummary setBackupFileName() Sets the current record's "backup_file_name" value
 * @method RoundSummary setRoundId() Sets the current record's "round_id" value
 * @method RoundSummary setMatch() Sets the current record's "Match" value
 * @method RoundSummary setMap() Sets the current record's "Map" value
 * @method RoundSummary setBestKiller() Sets the current record's "BestKiller" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoundSummary extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('round_summary');
        $this->hasColumn('id', 'integer', 20, [
            'primary' => true,
            'type' => 'integer',
            'autoincrement' => true,
            'length' => 20,
        ]);
        $this->hasColumn('match_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('map_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('bomb_planted', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('bomb_defused', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('bomb_exploded', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('win_type', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'bombdefused',
                1 => 'bombeexploded',
                2 => 'normal',
                3 => 'saved',
            ],
            'default' => 'normal',
        ]);
        $this->hasColumn('team_win', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'a',
                1 => 'b',
            ],
        ]);
        $this->hasColumn('ct_win', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('t_win', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('score_a', 'integer', 2, [
            'type' => 'integer',
            'length' => 2,
        ]);
        $this->hasColumn('score_b', 'integer', 2, [
            'type' => 'integer',
            'length' => 2,
        ]);
        $this->hasColumn('best_killer', 'integer', 20, [
            'type' => 'integer',
            'length' => 20,
        ]);
        $this->hasColumn('best_killer_nb', 'integer', 5, [
            'type' => 'integer',
            'length' => 5,
        ]);
        $this->hasColumn('best_killer_fk', 'boolean', null, [
            'type' => 'boolean',
        ]);
        $this->hasColumn('best_action_type', 'text', null, [
            'type' => 'text',
        ]);
        $this->hasColumn('best_action_param', 'text', null, [
            'type' => 'text',
        ]);
        $this->hasColumn('backup_file_name', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('round_id', 'integer', 5, [
            'type' => 'integer',
            'length' => 5,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Matchs as Match', [
            'local' => 'match_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('Maps as Map', [
            'local' => 'map_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('Players as BestKiller', [
            'local' => 'best_killer',
            'foreign' => 'id',
            'onDelete' => 'SET NULL']);

        $timestampable0 = new Doctrine_Template_Timestampable;
        $this->actAs($timestampable0);
    }
}
