<?php

/**
 * BasePlayersSnapshot
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $id
 * @property int $player_id
 * @property varchar $player_key
 * @property enum $first_side
 * @property enum $current_side
 * @property int $nb_kill
 * @property int $assist
 * @property int $death
 * @property int $point
 * @property int $hs
 * @property int $defuse
 * @property int $bombe
 * @property int $tk
 * @property int $nb1
 * @property int $nb2
 * @property int $nb3
 * @property int $nb4
 * @property int $nb5
 * @property int $nb1kill
 * @property int $nb2kill
 * @property int $nb3kill
 * @property int $nb4kill
 * @property int $nb5kill
 * @property int $pluskill
 * @property int $firstkill
 * @property int $round_id
 * @property Players $Player
 *
 * @method int getId() Returns the current record's "id" value
 * @method int getPlayerId() Returns the current record's "player_id" value
 * @method varchar getPlayerKey() Returns the current record's "player_key" value
 * @method enum getFirstSide() Returns the current record's "first_side" value
 * @method enum getCurrentSide() Returns the current record's "current_side" value
 * @method int getNbKill() Returns the current record's "nb_kill" value
 * @method int getAssist() Returns the current record's "assist" value
 * @method int getDeath() Returns the current record's "death" value
 * @method int getPoint() Returns the current record's "point" value
 * @method int getHs() Returns the current record's "hs" value
 * @method int getDefuse() Returns the current record's "defuse" value
 * @method int getBombe() Returns the current record's "bombe" value
 * @method int getTk() Returns the current record's "tk" value
 * @method int getNb1() Returns the current record's "nb1" value
 * @method int getNb2() Returns the current record's "nb2" value
 * @method int getNb3() Returns the current record's "nb3" value
 * @method int getNb4() Returns the current record's "nb4" value
 * @method int getNb5() Returns the current record's "nb5" value
 * @method int getNb1kill() Returns the current record's "nb1kill" value
 * @method int getNb2kill() Returns the current record's "nb2kill" value
 * @method int getNb3kill() Returns the current record's "nb3kill" value
 * @method int getNb4kill() Returns the current record's "nb4kill" value
 * @method int getNb5kill() Returns the current record's "nb5kill" value
 * @method int getPluskill() Returns the current record's "pluskill" value
 * @method int getFirstkill() Returns the current record's "firstkill" value
 * @method int getRoundId() Returns the current record's "round_id" value
 * @method Players getPlayer() Returns the current record's "Player" value
 * @method PlayersSnapshot setId() Sets the current record's "id" value
 * @method PlayersSnapshot setPlayerId() Sets the current record's "player_id" value
 * @method PlayersSnapshot setPlayerKey() Sets the current record's "player_key" value
 * @method PlayersSnapshot setFirstSide() Sets the current record's "first_side" value
 * @method PlayersSnapshot setCurrentSide() Sets the current record's "current_side" value
 * @method PlayersSnapshot setNbKill() Sets the current record's "nb_kill" value
 * @method PlayersSnapshot setAssist() Sets the current record's "assist" value
 * @method PlayersSnapshot setDeath() Sets the current record's "death" value
 * @method PlayersSnapshot setPoint() Sets the current record's "point" value
 * @method PlayersSnapshot setHs() Sets the current record's "hs" value
 * @method PlayersSnapshot setDefuse() Sets the current record's "defuse" value
 * @method PlayersSnapshot setBombe() Sets the current record's "bombe" value
 * @method PlayersSnapshot setTk() Sets the current record's "tk" value
 * @method PlayersSnapshot setNb1() Sets the current record's "nb1" value
 * @method PlayersSnapshot setNb2() Sets the current record's "nb2" value
 * @method PlayersSnapshot setNb3() Sets the current record's "nb3" value
 * @method PlayersSnapshot setNb4() Sets the current record's "nb4" value
 * @method PlayersSnapshot setNb5() Sets the current record's "nb5" value
 * @method PlayersSnapshot setNb1kill() Sets the current record's "nb1kill" value
 * @method PlayersSnapshot setNb2kill() Sets the current record's "nb2kill" value
 * @method PlayersSnapshot setNb3kill() Sets the current record's "nb3kill" value
 * @method PlayersSnapshot setNb4kill() Sets the current record's "nb4kill" value
 * @method PlayersSnapshot setNb5kill() Sets the current record's "nb5kill" value
 * @method PlayersSnapshot setPluskill() Sets the current record's "pluskill" value
 * @method PlayersSnapshot setFirstkill() Sets the current record's "firstkill" value
 * @method PlayersSnapshot setRoundId() Sets the current record's "round_id" value
 * @method PlayersSnapshot setPlayer() Sets the current record's "Player" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayersSnapshot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('players_snapshot');
        $this->hasColumn('id', 'integer', 20, [
            'primary' => true,
            'type' => 'integer',
            'autoincrement' => true,
            'length' => 20,
        ]);
        $this->hasColumn('player_id', 'integer', 20, [
            'type' => 'integer',
            'notnull' => true,
            'length' => 20,
        ]);
        $this->hasColumn('player_key', 'varchar', 255, [
            'type' => 'varchar',
            'length' => 255,
        ]);
        $this->hasColumn('first_side', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'ct',
                1 => 't',
                2 => 'other',
            ],
        ]);
        $this->hasColumn('current_side', 'enum', null, [
            'type' => 'enum',
            'values' => [
                0 => 'ct',
                1 => 't',
                2 => 'other',
            ],
        ]);
        $this->hasColumn('nb_kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('assist', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('death', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('point', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('hs', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('defuse', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('bombe', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('tk', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb1', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb2', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb3', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb4', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb5', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb1kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb2kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb3kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb4kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('nb5kill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('pluskill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('firstkill', 'integer', 5, [
            'type' => 'integer',
            'default' => 0,
            'length' => 5,
        ]);
        $this->hasColumn('round_id', 'integer', 5, [
            'type' => 'integer',
            'length' => 5,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Players as Player', [
            'local' => 'player_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $timestampable0 = new Doctrine_Template_Timestampable;
        $this->actAs($timestampable0);
    }
}
