<?php

/**
 * BaseAdvertising
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $id
 * @property int $season_id
 * @property varchar $message
 * @property bool $active
 * @property Seasons $Season
 *
 * @method int getId() Returns the current record's "id" value
 * @method int getSeasonId() Returns the current record's "season_id" value
 * @method varchar getMessage() Returns the current record's "message" value
 * @method bool getActive() Returns the current record's "active" value
 * @method Seasons getSeason() Returns the current record's "Season" value
 * @method Advertising setId() Sets the current record's "id" value
 * @method Advertising setSeasonId() Sets the current record's "season_id" value
 * @method Advertising setMessage() Sets the current record's "message" value
 * @method Advertising setActive() Sets the current record's "active" value
 * @method Advertising setSeason() Sets the current record's "Season" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertising extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advertising');
        $this->hasColumn('id', 'integer', 20, [
            'primary' => true,
            'type' => 'integer',
            'autoincrement' => true,
            'length' => 20,
        ]);
        $this->hasColumn('season_id', 'integer', 20, [
            'type' => 'integer',
            'length' => 20,
        ]);
        $this->hasColumn('message', 'varchar', 1000, [
            'type' => 'varchar',
            'length' => 1000,
        ]);
        $this->hasColumn('active', 'boolean', null, [
            'type' => 'boolean',
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seasons as Season', [
            'local' => 'season_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $timestampable0 = new Doctrine_Template_Timestampable;
        $this->actAs($timestampable0);
    }
}
