<?php

/**
 * BasesfGuardGroupPermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $group_id
 * @property int $permission_id
 * @property sfGuardGroup $Group
 * @property sfGuardPermission $Permission
 *
 * @method int getGroupId() Returns the current record's "group_id" value
 * @method int getPermissionId() Returns the current record's "permission_id" value
 * @method sfGuardGroup getGroup() Returns the current record's "Group" value
 * @method sfGuardPermission getPermission() Returns the current record's "Permission" value
 * @method sfGuardGroupPermission setGroupId() Sets the current record's "group_id" value
 * @method sfGuardGroupPermission setPermissionId() Sets the current record's "permission_id" value
 * @method sfGuardGroupPermission setGroup() Sets the current record's "Group" value
 * @method sfGuardGroupPermission setPermission() Sets the current record's "Permission" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardGroupPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_group_permission');
        $this->hasColumn('group_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);
        $this->hasColumn('permission_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardGroup as Group', [
            'local' => 'group_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('sfGuardPermission as Permission', [
            'local' => 'permission_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $timestampable0 = new Doctrine_Template_Timestampable([
        ]);
        $this->actAs($timestampable0);
    }
}
