<?php

/**
 * BasesfGuardUserPermission
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $user_id
 * @property int $permission_id
 * @property sfGuardUser $User
 * @property sfGuardPermission $Permission
 *
 * @method int getUserId() Returns the current record's "user_id" value
 * @method int getPermissionId() Returns the current record's "permission_id" value
 * @method sfGuardUser getUser() Returns the current record's "User" value
 * @method sfGuardPermission getPermission() Returns the current record's "Permission" value
 * @method sfGuardUserPermission setUserId() Sets the current record's "user_id" value
 * @method sfGuardUserPermission setPermissionId() Sets the current record's "permission_id" value
 * @method sfGuardUserPermission setUser() Sets the current record's "User" value
 * @method sfGuardUserPermission setPermission() Sets the current record's "Permission" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_permission');
        $this->hasColumn('user_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);
        $this->hasColumn('permission_id', 'integer', null, [
            'type' => 'integer',
            'primary' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', [
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $this->hasOne('sfGuardPermission as Permission', [
            'local' => 'permission_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $timestampable0 = new Doctrine_Template_Timestampable([
        ]);
        $this->actAs($timestampable0);
    }
}
