<?php

/**
 * BasesfGuardForgotPassword
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property int $user_id
 * @property string $unique_key
 * @property timestamp $expires_at
 * @property sfGuardUser $User
 *
 * @method int getUserId() Returns the current record's "user_id" value
 * @method string getUniqueKey() Returns the current record's "unique_key" value
 * @method timestamp getExpiresAt() Returns the current record's "expires_at" value
 * @method sfGuardUser getUser() Returns the current record's "User" value
 * @method sfGuardForgotPassword setUserId() Sets the current record's "user_id" value
 * @method sfGuardForgotPassword setUniqueKey() Sets the current record's "unique_key" value
 * @method sfGuardForgotPassword setExpiresAt() Sets the current record's "expires_at" value
 * @method sfGuardForgotPassword setUser() Sets the current record's "User" value
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardForgotPassword extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_forgot_password');
        $this->hasColumn('user_id', 'integer', null, [
            'type' => 'integer',
            'notnull' => true,
        ]);
        $this->hasColumn('unique_key', 'string', 255, [
            'type' => 'string',
            'length' => 255,
        ]);
        $this->hasColumn('expires_at', 'timestamp', null, [
            'type' => 'timestamp',
            'notnull' => true,
        ]);

        $this->option('symfony', [
            'form' => false,
            'filter' => false,
        ]);
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', [
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'CASCADE']);

        $timestampable0 = new Doctrine_Template_Timestampable([
        ]);
        $this->actAs($timestampable0);
    }
}
